# Generated by Django 5.2.7 on 2025-11-03 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_payroll_deductions_payroll_etat_paie_payroll_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='sector',
            field=models.CharField(choices=[('NON_AGRI', 'Non agricole'), ('AGRI', 'Agricole')], default='NON_AGRI', max_length=20),
        ),
        migrations.AddField(
            model_name='presence',
            name='holiday_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='presence',
            name='night_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='presence',
            name='overtime_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='presence',
            name='sunday_minutes',
            field=models.IntegerField(default=0),
        ),
    ]
