# Generated by Django 5.2.7 on 2025-11-06 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_employee_email_and_create_manager_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='auto_convert_to_cdi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contract',
            name='max_trial_renewals',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='contract',
            name='trial_renewals',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_contact',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='employees/photos/%Y/%m/%d/'),
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('leave_type', models.CharField(choices=[('PAID', 'Congé payé'), ('UNPAID', 'Congé sans solde'), ('SICK', 'Congé maladie'), ('MAT', 'Congé maternité/paternité'), ('OTHER', 'Autre')], default='PAID', max_length=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('REQUESTED', 'Requested'), ('DEPT_APPROVED', 'Dept Approved'), ('HR_APPROVED', 'HR Approved'), ('REFUSED', 'Refused'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('decision_note', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='leaves/%Y/%m/%d/')),
                ('dept_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dept_approvals', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='core.employee')),
                ('hr_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_approvals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
