# Generated by Django 5.2.7 on 2025-11-06 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_leavebalance'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='civil_status',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='osti_number',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='service',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[('ID', "Carte d'identité"), ('CV', 'CV'), ('DIPLOMA', 'Diplôme'), ('CONTRACT', 'Contrat'), ('CERT', 'Certificat'), ('PHOTO', 'Photo'), ('OTHER', 'Autre')], default='OTHER', max_length=32),
        ),
        migrations.CreateModel(
            name='PositionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_position', models.CharField(blank=True, max_length=128)),
                ('new_position', models.CharField(blank=True, max_length=128)),
                ('old_service', models.CharField(blank=True, max_length=128)),
                ('new_service', models.CharField(blank=True, max_length=128)),
                ('old_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('new_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_histories', to='core.employee')),
            ],
        ),
    ]
