# Generated by Django 5.2.7 on 2025-11-29 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_competency_message_performancereview_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='presence',
                    name='pause_excess_minutes',
                    field=models.IntegerField(default=0),
                ),
                migrations.AddField(
                    model_name='presence',
                    name='pause_minutes',
                    field=models.IntegerField(default=30),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        ALTER TABLE core_presence
                        ADD COLUMN IF NOT EXISTS pause_excess_minutes integer DEFAULT 0;
                        ALTER TABLE core_presence
                        ALTER COLUMN pause_excess_minutes SET DEFAULT 0;
                    """,
                    reverse_sql="""
                        ALTER TABLE core_presence
                        DROP COLUMN IF EXISTS pause_excess_minutes;
                    """,
                ),
                migrations.RunSQL(
                    sql="""
                        ALTER TABLE core_presence
                        ADD COLUMN IF NOT EXISTS pause_minutes integer DEFAULT 30;
                        ALTER TABLE core_presence
                        ALTER COLUMN pause_minutes SET DEFAULT 30;
                    """,
                    reverse_sql="""
                        ALTER TABLE core_presence
                        DROP COLUMN IF EXISTS pause_minutes;
                    """,
                ),
            ],
        )
    ]
